<a href="https://colab.research.google.com/github/pancenaunov76/pancenaunov76/blob/main/Copy_of_OK_homework_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Забелешка: ДОКОЛКУ НЕ Е НАПИШАНО ДА СЕ КОРИСТИ GROUPBY НЕ ТРЕБА ДА ГО КОРИСТИТЕ (ќе се смета за грешка)**

Import pandas

In [ ]:
import pandas as pd
import numpy as np

1. Креирајте серија преку листа која има 6 елементи. Потоа променете ги индексите да бидат буквите: A, B, C, D, E, F.

In [ ]:
l = [4, 5, 8, 9, 3, 2]
s = pd.Series(l)
s.index = ['A', 'B', 'C', 'D', 'E', 'F']
s

A    4
B    5
C    8
D    9
E    3
F    2
dtype: int64

2. Креирајте серија преку речник. Потоа променете ги индексите во вредности по ваш избор. Испринтајте ја серијата 2 пати, еднаш по самото креирање и еднаш по промената на индексите.

In [ ]:
dicti = {'A':[1, 7, 6]}
s2 = pd.Series(dicti)
print(s2)
s2.index = ['B']
s2

A    [1, 7, 6]
dtype: object

B    [1, 7, 6]
dtype: object

3. Креирајте празен dataframe

In [ ]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

4.1. Креирајте dataframe кој ќе има 3 колони: Име, Плата, Матичен Број. Пополнете ја табелата да има 10 редици. (име-стринг, плата-стринг (со $ пред секоја вредност), матичен број-стринг)

In [ ]:
d = {'Ime':['Petar', 'Gorgi', 'Dragan', 'Zoran', 'Igor', 'Irena', 'Mia', 'Marija', 'Gurga', 'Jana'], 'Plata':['$10', '$20', '$30', '$40', '$50', '$60', '$70', '$800', '$9000', '$1000'], 'Maticen_Broj':['416516166141', '5115165116', '987882417468', '5150001141', '65416545', '654651516', '89797879', '321311313', '963936993', '4941191991']}
d
df = pd.DataFrame(d)
df

      Ime  Plata  Maticen_Broj
0   Petar    $10  416516166141
1   Gorgi    $20    5115165116
2  Dragan    $30  987882417468
3   Zoran    $40    5150001141
4    Igor    $50      65416545
5   Irena    $60     654651516
6     Mia    $70      89797879
7  Marija   $800     321311313
8   Gurga  $9000     963936993
9    Jana  $1000    4941191991

4.2 Додадете нов ред кој ќе ги има следните вредности: име-Иле, плата-$2000, матичен број-1234567890123

In [ ]:
nov_red = {'Ime':'Ile', 'Plata':'$2000', 'Maticen_Broj':'1234567890123'}
df = df.append(nov_red,ignore_index=True)
df

<ipython-input-147-8d4f29a6da4e>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(nov_red,ignore_index=True)

       Ime  Plata   Maticen_Broj
0    Petar    $10   416516166141
1    Gorgi    $20     5115165116
2   Dragan    $30   987882417468
3    Zoran    $40     5150001141
4     Igor    $50       65416545
5    Irena    $60      654651516
6      Mia    $70       89797879
7   Marija   $800      321311313
8    Gurga  $9000      963936993
9     Jana  $1000     4941191991
10     Ile  $2000  1234567890123

4.3 Извадете ги сите информации за Иле.

In [ ]:
df[df['Ime']=='Ile']

    Ime  Plata   Maticen_Broj
10  Ile  $2000  1234567890123

4.4 Вредностите во колоната плата сменете ги да бидат цели броеви.

In [ ]:
df['Plata'] = df['Plata'].str.replace('$','').astype(int)
df

<ipython-input-17-bc1ddf292e98>:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  df['Plata'] = df['Plata'].str.replace('$','').astype(int)

       Ime  Plata   Maticen_Broj     Pol  Vozrast
0    Petar     10   416516166141    male       30
1    Gorgi     20     5115165116    male       56
2   Dragan     30   987882417468    male       25
3    Zoran     40     5150001141    male       47
4     Igor     50       65416545    male       60
5    Irena     60      654651516  female       19
6      Mia     70       89797879  female       29
7   Marija    800      321311313  female       32
8    Gurga   9000      963936993  female       31
9     Jana   1000     4941191991  female       35
10     Ile   2000  1234567890123    male       36

4.5 Додадете колона во која ќе го напишете полот на секоја личност. Додадете колона во која ќе ги напишете годините на секоја личност.

In [ ]:
df['Pol'] = ['male','male','male','male','male', 'female', 'female', 'female', 'female', 'female', 'male']
df['Vozrast']  = [30, 56, 25, 47, 60, 19, 29, 32, 31, 35, 36]
df

       Ime  Plata   Maticen_Broj     Pol  Vozrast
0    Petar     10   416516166141    male       30
1    Gorgi     20     5115165116    male       56
2   Dragan     30   987882417468    male       25
3    Zoran     40     5150001141    male       47
4     Igor     50       65416545    male       60
5    Irena     60      654651516  female       19
6      Mia     70       89797879  female       29
7   Marija    800      321311313  female       32
8    Gurga   9000      963936993  female       31
9     Jana   1000     4941191991  female       35
10     Ile   2000  1234567890123    male       36

4.6 Извадете ги сите машки од датсетот.

In [ ]:
df[df['Pol']=='male']

       Ime  Plata   Maticen_Broj   Pol  Vozrast
0    Petar     10   416516166141  male       30
1    Gorgi     20     5115165116  male       56
2   Dragan     30   987882417468  male       25
3    Zoran     40     5150001141  male       47
4     Igor     50       65416545  male       60
10     Ile   2000  1234567890123  male       36

4.7 Извадете ги сите женски и сите кои имаат плата повисока од 500.

In [ ]:
df[(df['Pol']=='female') & (df['Plata']>500)]

      Ime  Plata Maticen_Broj     Pol  Vozrast
7  Marija    800    321311313  female       32
8   Gurga   9000    963936993  female       31
9    Jana   1000   4941191991  female       35

4.8 Извадете ги сите кои имаат плата различна од 2000.

In [ ]:
df[~(df['Plata']==2000)]

      Ime  Plata  Maticen_Broj     Pol  Vozrast
0   Petar     10  416516166141    male       30
1   Gorgi     20    5115165116    male       56
2  Dragan     30  987882417468    male       25
3   Zoran     40    5150001141    male       47
4    Igor     50      65416545    male       60
5   Irena     60     654651516  female       19
6     Mia     70      89797879  female       29
7  Marija    800     321311313  female       32
8   Gurga   9000     963936993  female       31
9    Jana   1000    4941191991  female       35

4.9 Извадете ги матичните броеви на сите кои имаат помалку од 30 години или плата пониска од 700.

In [ ]:
df[(df['Vozrast']<30) | (df['Plata']<700)]

      Ime  Plata  Maticen_Broj     Pol  Vozrast
0   Petar     10  416516166141    male       30
1   Gorgi     20    5115165116    male       56
2  Dragan     30  987882417468    male       25
3   Zoran     40    5150001141    male       47
4    Igor     50      65416545    male       60
5   Irena     60     654651516  female       19
6     Mia     70      89797879  female       29

4.10 Извадете ги имињата на сите женски.

In [ ]:
df[df['Pol']=='female'].Ime

5     Irena
6       Mia
7    Marija
8     Gurga
9      Jana
Name: Ime, dtype: object

5. Симнете го датасетот и прочитајте го: [линк](https://drive.google.com/file/d/1CbghFo-6BZ5dtzARo7fCmF89k_WCV0XR/view?usp=sharing)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
ioan = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/loan (1).csv")
ioan

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,4009,1777,113.0,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,4158,709,115.0,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,3250,1993,126.0,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,5000,2393,158.0,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,9200,0,98.0,180.0,1.0,Rural

5.1 Колку колони и колку редови има датасетот?

In [ ]:
ioan.shape

(367, 12)

5.2 Извадете информации за датасетот (колку се празни вредности, каков тип на податок има во секоја колона и слично)

In [ ]:
ioan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            367 non-null    object
 1   Gender             356 non-null    object
 2   Married            367 non-null    object
 3   Dependents         357 non-null    object
 4   Education          367 non-null    object
 5   Self_Employed      344 non-null    object
 6   ApplicantIncome    367 non-null    int64
 7   CoapplicantIncome  367 non-null    int64
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB

5.3 Извадете ги сите омажени/оженети личности од датасетот кои имаат завршено факултет.

In [ ]:
ioan_ = ioan[(ioan['Married']=='Yes') & (ioan['Education']=='Graduate')]
ioan_

5.4 Која е личноста со највисок кредит?

In [ ]:
a = ioan[ioan['LoanAmount']==ioan['LoanAmount'].max()]['Loan_ID'].values
print(f'Najvisok kredit ima liceto koe go zelo kreditot so id {a}.')

Najvisok kredit ima liceto koe go zelo kreditot so id ['LP001791'].

5.5 За секоја должина на исплаќање на кредит, пресметајте колку е највисокиот кредит?

In [ ]:
period = ioan['Loan_Amount_Term'].unique()
print(period)
for i in period:
  #if i != 'NaN':
  kredit = ioan[ioan['Loan_Amount_Term']==i]['LoanAmount'].max()
  print(f'За должина на исплаќање на кредит од {i}, највисокиот кредит е {kredit}.')

[360. 240. 180.  nan  60. 480.  84.  12. 300. 350.  36. 120.   6.]
За должина на исплаќање на кредит од 360.0, највисокиот кредит е 550.0.
За должина на исплаќање на кредит од 240.0, највисокиот кредит е 280.0.
За должина на исплаќање на кредит од 180.0, највисокиот кредит е 185.0.
За должина на исплаќање на кредит од nan, највисокиот кредит е nan.
За должина на исплаќање на кредит од 60.0, највисокиот кредит е 139.0.
За должина на исплаќање на кредит од 480.0, највисокиот кредит е 149.0.
За должина на исплаќање на кредит од 84.0, највисокиот кредит е 132.0.
За должина на исплаќање на кредит од 12.0, највисокиот кредит е 260.0.
За должина на исплаќање на кредит од 300.0, највисокиот кредит е 152.0.
За должина на исплаќање на кредит од 350.0, највисокиот кредит е 133.0.
За должина на исплаќање на кредит од 36.0, највисокиот кредит е 118.0.
За должина на исплаќање на кредит од 120.0, највисокиот кредит е 80.0.
За должина на исплаќање на кредит од 6.0, највисокиот кредит е 95.0.

5.6 Од сите self employed личности во датасетот, извадете ги оние кои што имаат завршено факултет и имаат повеќе од 1 дете.

In [ ]:

a = ioan['Dependents'].unique()
a
# ioan['Dependents'] = ioan['Dependents'].str.replace('3+','3').astype(int)
b = ioan[(ioan['Education']=='Graduate') & (ioan['Dependents'].isin(['2', '3+'])) & (ioan['Self_Employed']=='Yes')]
b

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
144,LP001794,Male,Yes,2,Graduate,Yes,10890,0,260.0,12.0,1.0,Rural
156,LP001862,Male,Yes,2,Graduate,Yes,4246,4246,214.0,360.0,1.0,Urban
212,LP002172,Male,Yes,3+,Graduate,Yes,5384,0,150.0,360.0,1.0,Semiurban
224,LP002256,Female,No,2,Graduate,Yes,5184,0,187.0,360.0,0.0,Semiurban
246,LP002358,Male,Yes,2,Graduate,Yes,5000,2166,150.0,360.0,1.0,Urban
306,LP002721,Male,Yes,2,Graduate,Yes,7500,0,183.0,360.0,1.0,Rural
328,LP002806,Male,Yes,3+,Graduate,Yes,6958,1411,150.0,360.0,1.0,Rural

5.7 За секој тип на property пресметајте колку од луѓето кои земале кредите имаат завршено факултет и колку немаат.

In [ ]:
property = ioan['Property_Area'].unique()
for i in property:
  so_fakultet = ioan[(ioan['Property_Area']==i) & (ioan['Education']=='Graduate')]['Loan_ID'].nunique()
  bez_fakultet = ioan[(ioan['Property_Area']==i) & (ioan['Education']=='Not Graduate')]['Loan_ID'].nunique()
  print(f'Za Property_Area-{i} ima {so_fakultet} luge so zavrsen fakultet i {bez_fakultet} luge bez zavrsen fakultet.\n')

Za Property_Area-Urban ima 111 luge so zavrsen fakultet i 29 luge bez zavrsen fakultet.

Za Property_Area-Semiurban ima 87 luge so zavrsen fakultet i 29 luge bez zavrsen fakultet.

Za Property_Area-Rural ima 85 luge so zavrsen fakultet i 26 luge bez zavrsen fakultet.

6. Симнете го датасетот и прочитајте го. [линк](https://drive.google.com/file/d/1ngQzMRq5vowcaNQLhIDEwJftXLbQorqj/view?usp=sharing)

In [ ]:
city_df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/city_day.csv")
city_df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

In [ ]:
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

6.1 Додадете нова колона која ќе се вика year и ќе ја има годината за која станува збор за секој ред.

In [ ]:
city_df['Date'] = pd.to_datetime(city_df['Date'])
city_df['year'] = city_df['Date'].dt.year.astype(int)

city_df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket,year
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN,2015
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN,2015
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN,2015
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN,2015
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good,2020
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory,2020
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory,2020
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory,2020
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good,2020

6.2 За секоја година извадете ги имињата на градовите кои имале NO повисоко од 5.

In [ ]:
unique_year = city_df['year'].unique()
unique_year
for i in unique_year:
  city_name = city_df[(city_df['year']==i) & (city_df['NO']>5)]['City'].unique()
  print(f"Za godina {i}, NO>5 imale gradovite {city_name}.\n")
  #print(len(city_name))

Za godina 2015, NO>5 imale gradovite ['Ahmedabad' 'Bengaluru' 'Chennai' 'Delhi' 'Gurugram' 'Hyderabad'
 'Lucknow' 'Patna'].

Za godina 2016, NO>5 imale gradovite ['Ahmedabad' 'Bengaluru' 'Chennai' 'Delhi' 'Gurugram' 'Hyderabad'
 'Lucknow' 'Patna' 'Visakhapatnam'].

Za godina 2017, NO>5 imale gradovite ['Ahmedabad' 'Amaravati' 'Amritsar' 'Bengaluru' 'Chennai' 'Delhi'
 'Gurugram' 'Hyderabad' 'Jaipur' 'Jorapokhar' 'Lucknow' 'Patna'
 'Visakhapatnam'].

Za godina 2018, NO>5 imale gradovite ['Ahmedabad' 'Amaravati' 'Amritsar' 'Bengaluru' 'Brajrajnagar' 'Chennai'
 'Delhi' 'Gurugram' 'Hyderabad' 'Jaipur' 'Jorapokhar' 'Kolkata' 'Lucknow'
 'Mumbai' 'Patna' 'Talcher' 'Thiruvananthapuram' 'Visakhapatnam'].

Za godina 2019, NO>5 imale gradovite ['Ahmedabad' 'Amaravati' 'Amritsar' 'Bengaluru' 'Bhopal' 'Brajrajnagar'
 'Chandigarh' 'Chennai' 'Coimbatore' 'Delhi' 'Gurugram' 'Guwahati'
 'Hyderabad' 'Jaipur' 'Jorapokhar' 'Kolkata' 'Lucknow' 'Mumbai' 'Patna'
 'Talcher' 'Thiruvananthapuram' 'Visakhapatnam'].

Za godina 2020, NO>5 imale gradovite ['Ahmedabad' 'Aizawl' 'Amaravati' 'Amritsar' 'Bengaluru' 'Bhopal'
 'Brajrajnagar' 'Chandigarh' 'Chennai' 'Coimbatore' 'Delhi' 'Ernakulam'
 'Gurugram' 'Guwahati' 'Hyderabad' 'Jaipur' 'Jorapokhar' 'Kochi' 'Kolkata'
 'Lucknow' 'Mumbai' 'Patna' 'Talcher' 'Thiruvananthapuram' 'Visakhapatnam'].

6.3 Извадете ги имињата на градовите кои во 2018 години за CO имале вредност 0.89

In [ ]:
 a = city_df[(city_df['year']==2018) & (city_df['CO']==0.89)]['City'].unique()
print(f"Gradovi koi vo 2018 imale CO == 0.89 {a}.")

Gradovi koi vo 2018 imale CO == 0.89 ['Amaravati' 'Amritsar' 'Bengaluru' 'Chennai' 'Delhi' 'Gurugram'
 'Hyderabad' 'Jaipur' 'Lucknow' 'Patna' 'Thiruvananthapuram'
 'Visakhapatnam'].

6.4 За секој град пресметајте во кој месец (користете го полето Date) имал највисок NO2.

In [ ]:
city_df['Datum'] = pd.to_datetime(city_df['Date']).dt.month

unique_city = city_df['City'].unique()
unique_city

for i in unique_city:
  mesec = city_df[(city_df['City']==i) & (city_df['NO2']==city_df['NO2'].max())]['Datum'].values
  print(f"Gradot {i} najvisok NO2 imal vo mesec {mesec}.")

Gradot Ahmedabad najvisok NO2 imal vo mesec [].
Gradot Aizawl najvisok NO2 imal vo mesec [].
Gradot Amaravati najvisok NO2 imal vo mesec [].
Gradot Amritsar najvisok NO2 imal vo mesec [].
Gradot Bengaluru najvisok NO2 imal vo mesec [].
Gradot Bhopal najvisok NO2 imal vo mesec [].
Gradot Brajrajnagar najvisok NO2 imal vo mesec [].
Gradot Chandigarh najvisok NO2 imal vo mesec [].
Gradot Chennai najvisok NO2 imal vo mesec [].
Gradot Coimbatore najvisok NO2 imal vo mesec [].
Gradot Delhi najvisok NO2 imal vo mesec [].
Gradot Ernakulam najvisok NO2 imal vo mesec [].
Gradot Gurugram najvisok NO2 imal vo mesec [2].
Gradot Guwahati najvisok NO2 imal vo mesec [].
Gradot Hyderabad najvisok NO2 imal vo mesec [].
Gradot Jaipur najvisok NO2 imal vo mesec [].
Gradot Jorapokhar najvisok NO2 imal vo mesec [].
Gradot Kochi najvisok NO2 imal vo mesec [].
Gradot Kolkata najvisok NO2 imal vo mesec [].
Gradot Lucknow najvisok NO2 imal vo mesec [].
Gradot Mumbai najvisok NO2 imal vo mesec [].
Gradot Patna najvisok NO2 imal vo mesec [].
Gradot Shillong najvisok NO2 imal vo mesec [].
Gradot Talcher najvisok NO2 imal vo mesec [].
Gradot Thiruvananthapuram najvisok NO2 imal vo mesec [].
Gradot Visakhapatnam najvisok NO2 imal vo mesec [].

In [ ]:
city_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 18 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  datetime64[ns]
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
 16  year        29531 non-null  int64
 17  Datum       29531 non-null  int64
dtypes: datetime64[ns](1), float64(13), int64(2), object(2)
memory usage: 4.1+ MB

6.5 За кои градови имаме информации во датасетот?

In [ ]:
city_df['City'].unique()

array(['Ahmedabad', 'Aizawl', 'Amaravati', 'Amritsar', 'Bengaluru',
       'Bhopal', 'Brajrajnagar', 'Chandigarh', 'Chennai', 'Coimbatore',
       'Delhi', 'Ernakulam', 'Gurugram', 'Guwahati', 'Hyderabad',
       'Jaipur', 'Jorapokhar', 'Kochi', 'Kolkata', 'Lucknow', 'Mumbai',
       'Patna', 'Shillong', 'Talcher', 'Thiruvananthapuram',
       'Visakhapatnam'], dtype=object)

6.6 Извадете ги сите елементи за кои NH3 не е празна вредности и S02 е поголемо од 20.

In [ ]:
a = city_df[(city_df['NH3']=='non-null') & (city_df['SO2']>20)]
a

Empty DataFrame
Columns: [City, Date, PM2.5, PM10, NO, NO2, NOx, NH3, CO, SO2, O3, Benzene, Toluene, Xylene, AQI, AQI_Bucket, year]
Index: []

7. Симнете и прочитајте го датасетот: [линк](https://drive.google.com/file/d/1HbZN-k_FF2y3nm4dt3QTceA00J64VMco/view?usp=sharing)

In [ ]:
df_stations = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/stations.csv")
df_stations

7.1 За секој state пресметајте колку станици има.

In [ ]:
df_stations['State'].value_counts()

7.2 За секој град пресметајте колку станици има што се активни.

In [ ]:
df_stations[df_stations['Status']=='Active']['City'].value_counts()

8. Симнете го и прочитајте го датасетот: [линк](https://drive.google.com/file/d/1AddtE1MN6gW9dK6Q7eAzNgGjRU5DzSxw/view?usp=sharing)

In [ ]:
df_skin_care= pd.read_csv("/content/drive/MyDrive/Colab Notebooks/skin_care.csv")
df_skin_care

8.1 Избришете ја колоната Unnamed:0 .

In [ ]:
df_skin_care.drop('Unnamed: 0',axis=1,inplace=True)
df_skin_care

8.2 Со groupby за секоја цена на производите извадете која е средната вредност на ѕвезди кои ги има добиено.

In [ ]:
df_skin_care.groupby('price')['stars'].mean()

8.3 Барањето под 8.2 пресметајте го без groupby

In [ ]:
unique_price = df_skin_care['price'].unique()
unique_price
for i in unique_price:
  sredna_v = df_skin_care[df_skin_care['price']==i]['stars'].mean()

  print(f"Za cena {i}, sredna vrednost od dobieni dzvezdi e {sredna_v}.")

8.4 Кој е продуктот со најголем број на гласови?

In [ ]:
a = df_skin_care[df_skin_care['vote']==df_skin_care['vote'].max()]['title'].values[0]
a

8.5 За секој можност на добиени ѕвезди пресметајте кој е најскапиот производ.

In [ ]:
unique_stars = df_skin_care['stars'].unique().tolist()
#unique_stars
for i in unique_stars:
  max_price = df_skin_care[df_skin_care['stars']== i]['price'].max()
  #print(max_price)
  ime = df_skin_care[df_skin_care['price']== max_price]['title'].values[0]
  #print(ime)
  print(f"Za broj na dobieni dzvezdi {i}, najskapiot proizvod e '{ime}'")

9. Симнете го датасетот и вчитајте го: [линк](https://drive.google.com/file/d/1bsXNgnpktSOgx6jwMLWt8Gxm2qAZ1ynz/view?usp=sharing)

In [ ]:
df_cardio = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/cardio.csv")
df_cardio

9.1 Извадете ги сите кои имаат диабетис.

In [ ]:
df_cardio[df_cardio['diabetes']==1]['id'].values

9.2 Вредностите на колоната is_smoking променете ги: сите што се YES да станат True, сите што се No да станат False.

In [ ]:
df_cardio['is_smoking']=='YES'

9.3 За сите категории на едукација извадете го id-то на личноста што има највисок heart rate.

In [ ]:
unique_education = df_cardio['education'].unique()
#unique_education
for i in unique_education:
  lice = df_cardio[(df_cardio['education']==i) & (df_cardio['heartRate']==df_cardio['heartRate'].max())]['id'].values
  print(f"Za stepen na edukacija {i}, najvisok heart rate ima licnosta so id {lice}.")

9.4 Со groupby пресметајте за секоја возраст колку е нависоката вредност за totChol.

In [ ]:
df_cardio.groupby('age')['totChol'].max()

9.5 Барањето под 9.4 пресметајте го без groupby.

In [ ]:
unique_age = df_cardio['age'].unique()
unique_age
for i in unique_age:
  max_chol = df_cardio[df_cardio['age']==i]['totChol'].max()
  print(f"Za vozrast od {i} godini, max vrednost za totChol e{max_chol}.")

9.6 За сите можности на пол пресметајте колку луѓе се пушачи и колку не се.

In [ ]:
unique_sex = df_cardio['sex'].unique()
#unique_sex
for i in unique_sex:
  smoker = df_cardio[(df_cardio['sex']==i) & (df_cardio['is_smoking']=='YES')]['id'].nunique()
  nonsmoker = df_cardio[(df_cardio['sex']==i) & (df_cardio['is_smoking']=='NO')]['id'].nunique()
  print( i,smoker,nonsmoker)

9.7 Извадете ги сите ids кои имаат diaBP поголемо од 70 и MI помало од 25.

In [ ]:
df_cardio[(df_cardio['diaBP']>70) & (df_cardio['BMI']<25)]['id'].values

9.8 Колку луѓе пушат по 20 цигари на ден?

In [ ]:
df_cardio[df_cardio['cigsPerDay']==20]['id'].nunique()